workflows:
  version: 2
  build-deploy:
    jobs:
      - test

version: 2
jobs:
  test:
    docker:
      - image: circleci/python:2-jessie
    parallelism: 2
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: busy
          command: |
            trap "echo stoping;sleep 30;echo stopped" EXIT
            sleep 180
