workflows:
  version: 2
  build-deploy:
    jobs:
      - test

version: 2
jobs:
  test:
    docker:
      - image: circleci/python:2-jessie
    #docker:
    #  - image: aeternity/builder
    #    user: builder
    #working_directory: ~/epoch
    parallelism: 2
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: move tests
          command: |
            export CIRCLE_TOKEN=${CCI_DOT_COM_TOKEN}
            mkdir -p _build/test/logs
            cd _build/test/logs
            curl "https://circleci.com/api/v1.1/project/github/aeternity/epoch/13616/artifacts?circle-token=$CIRCLE_TOKEN" | grep 'junit' | grep -o 'https://[^"]*/'${CIRCLE_NODE_INDEX}'/[^"]*' > artifacts.txt
            <artifacts.txt xargs -P4 -I % wget %?circle-token=$CIRCLE_TOKEN
            # Remove query string from a static resource.
            find . -type f -name "*\?*" -exec ../../../.circleci/removeQuery.sh {} \;
            rm -f artifacts.txt
      - run:
          name: sumarize tests
          command: |
            echo "contain DOT EXTENSION"
            grep -r '\.xml\|\.junit\|\.cucumber' .
            echo "named DOT EXTENSION"
            find . -type f -name '*.xml'
            find . -type f -name '*.junit'
            find . -type f -name '*.cucumber'
      - run:
          name: remove conflicts file
          command: |
            rm _build/test/logs/ctlog.html
            rm _build/test/logs/variables-epoch_ct@localhost

      - store_test_results:
          path: _build/test/logs
      - store_artifacts:
          path: _build/test/logs
