workflows:
  version: 2
  build-deploy:
    jobs:
      - test

version: 2
jobs:
  test:
    docker:
      - image: circleci/python:2-jessie
    #docker:
    #  - image: aeternity/builder
    #    user: builder
    #working_directory: ~/epoch
    parallelism: 2
    working_directory: ~/repo
    steps:
      - checkout
      - save_cache:
          key: source-cache
          paths:
            - ".git"
