workflows:
  version: 2
  build-deploy:
    jobs:
      - test

version: 2
jobs:
  test:
    parallelism: 2
    docker:
      - image: circleci/python:2-jessie
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: move tests
          command: |
            mkdir -p reports/junit
            mv tesresults${CIRCLE_NODE_INDEX}.xml reports/junit/junit.xml
      - store_test_results:
          path: reports
      - store_artifacts:
          path: reports
