workflows:
  version: 2
  build-deploy:
    jobs:
      - test

version: 2
jobs:
  test:
    docker:
      - image: circleci/python:2-jessie
    #docker:
    #  - image: aeternity/builder
    #    user: builder
    #working_directory: ~/epoch
    parallelism: 2
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: stage tests
          command: |
            export CIRCLE_API_TOKEN=${CCI_DOT_COM_TOKEN}
            curl https://gist.githubusercontent.com/eddiewebb/9bda93977659d954d705ca623ff452af/raw/downloadArtifacts.sh | bash -s aeternity/epoch 13259 github 200
            mv -a CIRCLE_NODE_INDEX/home/builder/epoch/* .
      - run:
          name: move tests
          command: |
            mkdir _build/test/reports
            mv _build/test/logs/junit.xml _build/test/reports/

      - store_test_results:
          path: _build/test/reports
      - store_artifacts:
          path: _build/test/logs
