workflows:
  version: 2
  build-deploy:
    jobs:
      - test

version: 2
jobs:
  test:
    docker:
      - image: aeternity/builder
        user: builder
    working_directory: ~/epoch
    parallelism: 2
    docker:
      - image: circleci/python:2-jessie
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: move tests
          command: |
            mkdir -p _build/test/logs
            mv tesresults${CIRCLE_NODE_INDEX}.xml _build/test/logs/junit.xml
      - store_test_results:
          path: _build/test/logs
      - store_artifacts:
          path: _build/test/logs
