workflows:
  version: 2
  build-deploy:
    jobs:
      - test

version: 2
jobs:
  test:
    docker:
      - image: circleci/python:2-jessie
    parallelism: 2
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: busy
          command: |
            trap "echo stoping && sleep 30 && echo stopped" EXIT
            sleep 180
      - run:
          name: always
          when: always
          command: |
            echo "always command"
            sleep 20
            echo "always done"

      - run:
          name: fail
          when: on_fail
          command: |
            echo "fail command"
            sleep 20
            echo "fail done"

      - run:
          name: i dont think this is vali
          when: on_cancel
          command: |
            echo "fail command"
            sleep 20
            echo "fail done"
